name: Deploy to GitHub Pages via gh-pages branch

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Para que github_token funcione en los siguientes pasos

      # 2) Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: latest

      # 3) Build
      - name: Install deps & Build
        run: |
          bun install
          bun run build

      # 4) Deploy to gh-pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
          clean: true
          commit-message: "chore: deploy to gh-pages [skip ci]"
